### ISSUE TITLE
It does not work with angular 8.0.0 and ivy enabled

### ISSUE THREAD

**Issue by sysmat** [kekeh/mydatepicker#595]
It doesn't compile  

`ERROR in node_modules/mydatepicker/dist/my-date-picker.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class`

Regards Tomaž

**Comment by kekeh** [comment]
can you try this newer datepicker: https://github.com/kekeh/angular-mydatepicker

**Comment by imirkin** [comment]
Looks like there's a solution for this issue here:

https://github.com/angular/angular/issues/32729#issuecomment-535631498

This worked for me (with the updated component that no longer uses Renderer).

**Comment by shahafal** [comment]
Hi I'm having the same issue with Angular 9.0.6 and Mydatepicker 2.6.9.

I tried the solution here: https://github.com/angular/angular/issues/32729#issuecomment-535631498
with giving the ngcc a hint on the package, but I'm getting:

> Error: Error when flattening the source-map "C:/Home/Websites/RedBoard/2019/rbb-client/node_modules/mydatepicker/bundles/mydatepicker.umd.js.map" for "/node_modules/mydatepicker/bundles/mydatepicker.umd.js": RangeError: Maximum call stack size exceeded

and then when I run `ng build --prod` I'm getting:

> ERROR in Cannot resolve type entity ɵngcc2.FocusDirective to symbol

I saw you have a new Angular-Mydatepicker project, bug it has a few things that are preventing me from using it (most importantly it has a different UX, and then it's also missing some options, and have a bug when using date-limit).
This project (not the new angular-datepicker) is a really good one, please don't deprecate it for Angular 9+.

**Comment by imirkin** [comment]
FWIW, my testing of that solution was with 9.0.0-rc.7 . Haven't tried it since, as ivy increases bundle sizes by like 50% (which works out to multiple megabytes in my case). I do remember things being "fiddly" as you move between angular versions -- I'd recommend trying to just rm -rf node_modules and see if that helps any.

**Comment by ofirrifo** [comment]
I have the same issue as @shahafal wrote.
I have an Angular 8 project which deepened on this package.
I'm trying to upgrade to angular 9 and I'm struggling with the same issues @shahafal  wrote. 

I saw that you create a new package **Angular-Mydatepicker** but I can't use it 
is it has a different UX and Styling.

Please upgrade this mydatepicker package to lasted angular version.

Thanks :)

**Comment by imirkin** [comment]
FWIW I looked briefly at angular-mydatepicker, but it's not an upgrade. It's just a different package with similar functionality. Perhaps it's even better, but it's just a different thing that will require non-trivial development to achieve feature-parity for existing integrations wrt styling, options, etc.

**Comment by ofirrifo** [comment]
Whey not to upgrade this package to latest angular version ?

**Comment by kekeh** [comment]
Hi @ofirrifo 

Can you try this version? If it works I will then publish it to npm. Your Angular version should be 9.

[mydatepicker-9.0.0.zip](https://github.com/kekeh/mydatepicker/files/4398433/mydatepicker-9.0.0.zip)

**Instructions**

1. Unzip file save unzipped file to disk
2. npm install <path_to_file>/mydatepicker-9.0.0.tgz

**Comment by ofirrifo** [comment]
@kekeh 
Thanks I will check it.

Appreciate your fast response :)

**Comment by kekeh** [comment]
I created separate branch to the **Angular 9** version of this library. You can install Angular 9 version as follows: **npm install --save mydatepicker@ng9**

I also created Angular 9 project with the angular/cli and put this library to the project. I didn't see any problems. The following command worked without problems:
- ng serve
- ng build --prod

**Comment by ofirrifo** [comment]
@kekeh 
Thanks a lot I'm just trying to do it now.
I need your help with this **mydaterangepicker** package as well

node_modules/mydaterangepicker/dist/my-date-range-picker.component.d.ts:1:73 - error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

I'm getting this error
1 import { EventEmitter, OnChanges, OnDestroy, SimpleChanges, ElementRef, Renderer, ChangeDetectorRef } from "@angular/core";
                                                                          ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5730:31
    5730 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

**Comment by kekeh** [comment]
Hi @ofirrifo 

**mydaterangepicker** module is not updated. As you can see from the error there is still **Renderer** used and I don't have any plan to update it. Can you consider **angular-mydatepicker**. It is datepicker and daterangepicker with many better features.

Styling is not a problem because you can easily set your own style to the component. There are also predefined styles available.

Try it here: https://kekeh.github.io/angular-mydatepicker/

Select predefined style from the **Override style** dropdown and open the calendar. You can also create your own theme based on this https://github.com/kekeh/angular-mydatepicker/wiki/color-theme-(grey) template.

**Comment by ofirrifo** [comment]
@kekeh 
Currently I'm trying to upgrade my project from angular 8 to 9.

I really appreciate if you can change the Renderer to Renderer2.

BTW I would happy if we can talk via zoom.

Please let me know :)

**Comment by kekeh** [comment]
Renderer is not only problem in mydaterangepicker project. There are something else but I don't know what and I don't know how fix them. 

In mydatepicker project I created totally new angular/cli library project and copy code from old to new one. Also there were some code changes.

**Comment by shahafal** [comment]
@kekeh the new angular 9 version of mydatepicker (`npm install --save mydatepicker@ng9`) worked like a charm! thanks

**Comment by ofirrifo** [comment]
@kekeh 
I will create tommorow a new library from your range date picker that will support angular 9.

Today I clone your project and succeeded to create a new project that run your code with angular 9 after I update the old Renderer to use the Renderer2.

And than maybe you can add the new code to your repo.

I would like to talk with you via zoom if it ok with you.

**Comment by kekeh** [comment]
Hello @ofirrifo 

Thank you but, I can update mydaterangepicker. It is my job and I know exactly what to do because I have already done it once. Component will be ready this evening.

**Comment by sysmat** [comment]
When using ng 9 the lib should not be publish with ivy, which is default, so just disable ivy.
tsconfig.lib.json:

```json
"angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true,
    "enableIvy": false
  }
 
```

**Comment by ofirrifo** [comment]
@kekeh Thanks I'm really appreciate it.

**Comment by kekeh** [comment]
@ofirrifo You can now install **Angular 9** version of **mydaterangepicker** as follows: **npm install --save mydaterangepicker@ng9**

**Comment by kekeh** [comment]
> When using ng 9 the lib should not be publish with ivy, which is default, so just disable ivy.
> tsconfig.lib.json:
> 
> ```json
> "angularCompilerOptions": {
>     "skipTemplateCodegen": true,
>     "strictMetadataEmit": true,
>     "fullTemplateTypeCheck": true,
>     "strictInjectionParameters": true,
>     "enableResourceInlining": true,
>     "enableIvy": false
>   }
>  
> ```

Thanks! It was disabled only from the **tsconfig.prod.lib.json** file but, now it is also fixed to the **tsconfig.lib.json** file.

**Comment by ofirrifo** [comment]
@kekeh Thanks :)

**Comment by ofirrifo** [comment]
@kekeh it working perfect thanks :)
